<a href="https://colab.research.google.com/github/shruti123-web/INTM584_IES_/blob/main/INTM584_IES_Lec13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy stores the data as a series
import numpy as np
kanto = [73, 67,43]
kanto = np.ndarray([73, 67, 43])
kanto

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:
kanto = np.array([73, 67, 43])
kanto

array([73, 67, 43])

In [ ]:
x = np.zeros([5,3])
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
y=np.array([[1,2],[3,4]])
y

array([[1, 2],
       [3, 4]])

In [ ]:
y[1]

array([3, 4])

In [ ]:
y[0][1]

2

In [ ]:
y[0,0]

1

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,6,7]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 6, 7]])

In [ ]:
x.max()

7

In [ ]:
arr1 = np.arange(4, dtype = np.float)

<ipython-input-12-b749bfb5c289>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.arange(4, dtype = np.float)


In [ ]:
arr1 = np.arange(4)
arr1

array([0, 1, 2, 3])

In [ ]:
arr2 = arr1.reshape(2,2)
arr2

array([[0, 1],
       [2, 3]])

In [ ]:
x = np.array([[1,2],[2,3]])
y = np.array([[1,1],[1,1]])
print(x,y)
np.add(x,y)

[[1 2]
 [2 3]] [[1 1]
 [1 1]]


array([[2, 3],
       [3, 4]])

In [ ]:
np.subtract(x,y)

array([[0, 1],
       [1, 2]])

In [ ]:
np.multiply(x,y)

array([[1, 2],
       [2, 3]])

In [ ]:
np.divide(x,y)

array([[1., 2.],
       [2., 3.]])

In [ ]:
np.power(x,2)

array([[1, 4],
       [4, 9]])

In [ ]:
#API-> Application Interface , client server , to communicate between two diff entities with min. info.

In [ ]:
#Eg.-> UPI-> PhonePay

#3 types of API
#PRIVATE
#PUBLIC
#PARTNER

In [ ]:
#methods of API
#GET-> GET THE DATA
#POST-> SEND THE DATA
#PUT-> UPDATE THE DATA
#DELETE-> DELETE THE DATA